### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by hal-codebot** [jessesquires/sandbox-gh-workflows#59]
🤖 _This issue was automatically generated by the `Start Release Process` workflow._

📝 _You can [edit this template here](https://github.com/gethopscotch/hopscotch-iPad/blob/main/.github/release_checklist.md)._

# 1.2.3 Release Checklist

Please refer to our [Release Process documentation](https://github.com/gethopscotch/hopscotch-iPad/blob/main/docs/release_process.md).

## Pre-release

- [ ] [product] Complete [user critical path checklist](https://airtable.com/appdwdLvIgSz7KBE4/tblrW7Wx4gbTC1rrG/viwbDJ0VKZkT8gDj4?blocks=hide).
- [ ] [product] Ensure there are translations stories (Spanish + Chinese).
- [ ] [product] Check that metadata (screenshots, release notes, etc.) on App Store Connect is up-to-date.
    - [ ] [dev] If needed, submit a PR to the `release/*` branch with any updates or changes to App Store metadata.
- [ ] [dev] See: [Managing The Release](https://github.com/gethopscotch/hopscotch-iPad/blob/main/docs/release_process.md#managing-the-release) docs.

## App Store Submission

- [ ] Submit release to the App Store, [per our documentation](https://github.com/gethopscotch/hopscotch-iPad/blob/main/docs/release_process.md#submit-to-the-app-store).
- [ ] [product] Begin drafting blog post (optional).
- [ ] Wait for approval.

## Post-approval

- [ ] Release the app on App Store Connect. **Only do this during working hours, so dev team can be on hand.**
- [ ] [dev] Run the `Finish Release` Workflow on GitHub Actions. Consult our [documentation](https://github.com/gethopscotch/hopscotch-iPad/blob/main/docs/release_process.md#finishing-the-release) for details.
- [ ] [dev] If needed, set the latest project version on AWS to the version you are releasing (editor version). **Note:** this might not have changed (it usually does not).
- [ ] [dev] If there are WebPlayer changes, update the production WebPlayer to the latest version. **Ensure that we bump the minor version or major version as appropriate.**
- [ ] [product] Message `@channel` in [Slack `#general`](https://hopscotch-chat.slack.com/archives/C02BQGWJB) that the app has been released.
- [ ] [product] Amplitude Updates
    - [ ] Add a release in Amplitude for App Store By Device. The name should be a summary of main changes. The description should have full release notes.
    - [ ] Make a dashboard on amplitude to track new release (optional).
    - [ ] Annotate the new events in amplitude for both Hopscotch App Store and App Store By Device. _The new events should have descriptions of what actions will trigger them plus screenshots if possible._
- [ ] [product] Post to the forum about new release + close threads for issues we've fixed.
- [ ] Schedule team demo (optional).
- [ ] [product] Post blog post to website (optional).
- [ ] [product] Email update (for major releases only).
