### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by hal-codebot** [jessesquires/sandbox-gh-workflows#61]
🤖 _This issue was automatically generated by the [`Start Release Process` workflow](https://github.com/jessesquires/sandbox-gh-workflows/actions/workflows/start-release-process.yml)._

📝 _You can [edit this template here](https://github.com/jessesquires/sandbox-gh-workflows/blob/main/.github/release_checklist.md)._

# 1.2.3 Release Checklist

- [ ] These are some manual steps
- [ ] That you should not forget to do
- [ ] When creating a new release
- [ ] Good luck!
